version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./server/assets:/app/assets
    networks:
      - app-network
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://192.168.0.14:8080
    volumes:
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge