version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080
    volumes:
      - ./backend:/app
      - ./assets:/app/assets
    command: go run main.go  # Use air or realize for hot reload
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start  # Development server with hot reload
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge